package mysql

const (
	NODE_INSERT_ON_DUPLICATE_KEYS = ``
	NODE_DELETE = ``
	NODE_QUERY_BY_NODENAME = ``

	TEMPLATE_INSERT_ON_DUPLICATE_KEYS = ``
	TEMPLATE_DELETE = ``
	TEMPLATE_QUERY_BY_TEMPLATENAME = ``

	OPERATIONLOG_INSERT = ``
	OPERATIONLOG_DELETE = ``
	OPERATIONLOG_QUERY_RECENT_100 = ``
)


